### ISSUE TITLE
Use correct data types for columns containing air quality measurements

### ISSUE THREAD

**Issue by equivalentideas** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#10]
So that we can work with and doc calculations on the data.

We'll have to migrate the existing data.

**Comment by equivalentideas** [comment]
Here's that initial work I did yesterday https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/tree/convert_column_type_for_floats

**Comment by henare** [comment]
It looks like `pm2_5_concentration_ug_per_m3` should be stored as an Integer and the remaining eight values should be stored as Floats (will [get stored](http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-Column+types) as `double precision` by Postgres).

**Comment by henare** [comment]
>It looks like pm2_5_concentration_ug_per_m3 should be stored as an Integer...

The data published by the NSW government (see #18) isn't an Integer so this should also be a Float. That makes things easy.
