### ISSUE TITLE
Set up monitoring of the Heroku scheduled job so we know if there's an error

### ISSUE THREAD

**Issue by equivalentideas** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#12]
This addon seems to be the recommended way to do this https://elements.heroku.com/addons/deadmanssnitch

**Comment by henare** [comment]
This addon is now provisioned and set up.

It's pretty crude though, at least on the free plan. We only get notified if the job doesn't work for an hour (so if it starts failing we'll miss up to an hour of data). If there's an exception we don't get told what it is (but I guess we can check the Heroku logs).

**Comment by equivalentideas** [comment]
Nice one @henare 👍 Let's see how this goes.
