### ISSUE TITLE
Don't store unit of measurement with values in database

### ISSUE THREAD

**Issue by henare** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#13]
We're currently storing the unit of measurement along with the value (e.g. _18.0 **(µg/m³)**_):

![screenshot from 2018-03-20 10-02-30](https://user-images.githubusercontent.com/48945/37626882-e7d75046-2c25-11e8-9bcf-d06828f814e1.png)

Presuming the unit of measurement doesn't change, we should only store the value rather than repeatedly storing the measurement unit.

This relates to #10 because when we start storing values using the correct datatype we won't be able to include the string unit of measurement anyway.

* [x] Strip the units before saving (done in https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/commit/4f153fd22bc27b3720440f65ce96ce401e38a9aa)
* [x] Remove units from existing data (was [done manually](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/issues/13#issuecomment-374774800) but we [retrospectively added a migration](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/pull/30/commits/730aff54278746e7483c161f58ba0d4d54a3294f))
* [x] change the column names to include the units (#20)

**Comment by equivalentideas** [comment]
@henare Do you think we should move the units into the column names? That seems to make sense so that someone looking at a CSV version of the table or something can still make sense of it without the readme.

**Comment by henare** [comment]
@equivalentideas yeah I think that's a good idea :+1:

**Comment by equivalentideas** [comment]
Removed units from all the records in production with:

```
heroku run --app westconnex-m4-east-air-quality -e bundle exec irb

require_relative 'database.rb'

def extract_value(string)
  string.split(' ').first
end

AqmRecord.find_each do |record|
  record.update!(
    pm2_5_concentration: extract_value(record.pm2_5_concentration),
    pm10_concentration: extract_value(record.pm10_concentration),
    co_concentration: extract_value(record.co_concentration),
    no2_concentration: extract_value(record.no2_concentration),
    differential_temperature_lower: extract_value(record.differential_temperature_lower),
    differential_temperature_upper: extract_value(record.differential_temperature_upper),
    wind_speed: extract_value(record.wind_speed),
    wind_direction: extract_value(record.wind_direction),
    sigma: extract_value(record.sigma)
  )
end
```

I then checked the result with the csv
