### ISSUE TITLE
Scrape JSON files instead of HTML pages

### ISSUE THREAD

**Issue by henare** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#29]
We're currently using PhantomJS to scrape the [HTML pages](http://airodis.ecotech.com.au/westconnex/) with JS enabled. Those pages are actually populated by JSON files, e.g. http://airodis.ecotech.com.au/AirodisReport/JobSubmit.ashx?report=West+Connex%5cWebsite%5cChandos+St+summary.xml&format=json which should be easier and more reliable to fetch.

**Comment by equivalentideas** [comment]
@henare for notes, this is what I came up with on the plane https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/pull/57

The tests don't actually work, but you can see where I was going with it for interests sake.

**Comment by henare** [comment]
@equivalentideas thanks! Interesting we both came up with similar ideas of removing the auto-discovery of feed locations and replacing that with a static lookup :smile: 

Switching what I've done in #56 to use VCR instead of a manually downloaded fixture file might be an improvement to do in the future?

**Comment by equivalentideas** [comment]
> Switching what I've done in #56 to use VCR instead of a manually downloaded fixture file might be an improvement to do in the future?

Yep that sounds good 👍

**Comment by henare** [comment]
Closed by [merging #56](https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/pull/56#issuecomment-391212278).
