### ISSUE TITLE
Fix handling of dates and times

### ISSUE THREAD

**Issue by equivalentideas** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#32]
We have two columns that save dates and times, `scraped_at` and `latest_reading_recorded_at`. These currently are stored as strings and are stored as different timezones. We should:

- [x] change the column type of `scraped_at` to a proper time type (#46 )
- [x] Create a new column to store the original date that was collected (in case we need to recreate or audit this) (https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/pull/49/files#diff-b9878e7245f2afae10f27f6ad43e4a9d)
- [x] Transform the existing `lastest_reading_recorded_at` to UTC. Create a method that can parse what we've collected, which can be used in updating what we've collected and parsing the data during scrapes. (https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/pull/49/files#diff-a8baaea5ee65c810ab7ea0ce9d475b95)
- [x] Ensure all times saved in the database are UTC
- [x] Update the column type of `lastest_reading_recorded_at` to DateTime.
- [ ] Make times in the downloaded data NSW local time (#50)

**Comment by henare** [comment]
Also the filename added in #37 should be NSW time.

**Comment by henare** [comment]
I've been working on this and found that the parsing of `latest_reading_recorded_at` is a real pain. Because it's evaluated by JavaScript with our current scraper we get different results between Heroku and locally.

I think before tackling this it would be better to fix #29.

**Comment by henare** [comment]
Oh I should also say that I've done a lot of checks and think we should just consider the current values in `latest_reading_recorded_at` as having a timezone of +10, i.e. they didn't adjust their timezone to DST and haven't changed anything since.

There's heaps of messed up times, including St Luke's being 1 hour behind all the other monitors from April 1 03:00 Sydney time to April 4 09:00 Sydney time, but I think the above solution is the cleanest for the data we already have.

**Comment by equivalentideas** [comment]
We're chatting, and think the first step is writing the method to convert the record dates to UTC. Start there.

**Comment by equivalentideas** [comment]
Working on this here https://github.com/equivalentideas/westconnex_M4_East_Air_Quality_Monitoring/tree/convert_time

**Comment by henare** [comment]
Closing now that #49 is merged and deployed.
