### ISSUE TITLE
What proportion of recordings have a value of PM 2.5. over 8?

### ISSUE THREAD

**Issue by equivalentideas** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#47]
I did this in PostgreSQL. For Haberfield Public School:

```
SELECT COUNT(*) FROM aqm_records
WHERE location_name = 'Haberfield Public School AQM' AND
pm2_5_concentration_ug_per_m3 IS NOT NULL AND
pm2_5_concentration_ug_per_m3 >= 0;
 count
-------
  5373
(1 row)

SELECT COUNT(*) FROM aqm_records
WHERE location_name = 'Haberfield Public School AQM' AND
pm2_5_concentration_ug_per_m3 IS NOT NULL AND
pm2_5_concentration_ug_per_m3 >= 0 AND
pm2_5_concentration_ug_per_m3 > 8;
 count
-------
  4748
(1 row)
```

4748 / 5373 = 88.37

**Comment by henare** [comment]
I just downloaded the CSV and used the spreadsheet to count these values again. I get:

* Total records for Haberfield: 5907
* PM2.5 >= 0 (i.e. null and negatives removed): 5767
* PM2.5 >= 8: 5294

That gives 5767/5284 = 91.8%

Here's some more proportions:

* PM2.5 >= 10: 78.8%
* PM2.5 >= 15: 27.9%
* PM2.5 >= 20: 7%
* PM2.5 >= 25: 2%
