### ISSUE TITLE
Scraper saving wrong value for "Latest reading recorded at"

### ISSUE THREAD

**Issue by henare** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#54]
Since #51 was deployed the "Latest reading recorded at" value has been recorded incorrectly, i.e. what it's recording is different to what I see in my web browser.

It appears to be 10 hours behind what it should be. Interestingly the corresponding `latest_reading_recorded_at_raw` is the same. That indicates the cause of the problem is the change in timezone that's being picked up by PhantomJS and rendered by the JavaScript engine.

**Comment by henare** [comment]
The last correctly recorded reading is `2018-05-01 21:40:00 +1000` and the immediate next reading, that's incorrect, is `2018-05-01 12:00:00 +1000`.

**Comment by equivalentideas** [comment]
I wanted to look at some recent records, so I downloaded the lastest database locally and then in the `pry` console ran:

```
require_relative 'lib/aqm_record'

AqmRecord.where(Sequel.lit('id > ?', 40090)).each do |record|
  next unless record.values[:latest_reading_recorded_at]
  corrected_time = record.values[:latest_reading_recorded_at] + (60 * 60 * 10)
  record.update(latest_reading_recorded_at: corrected_time)
  record.save
end
```

Quick fix so I could export a csv with the correct times.
