### ISSUE TITLE
Use SQLite in development

### ISSUE THREAD

**Issue by henare** [equivalentideas/westconnex_M4_East_Air_Quality_Monitoring#7]
So it's really easy to get up and running. We're using ActiveRecord anyway so this should be pretty easy.

**Comment by equivalentideas** [comment]
From #9 

> Maybe the intent was in fact
to use PostgreSQL to ensure complete parity between development and production?
If so I'm happy for this and the associated issue to be closed ⚡️

> Yeah that's what I was thinking while this is still quite hacky. I agree this would be easier not to run postgres locally, but it feels like too early an optimisation to me 

I’d rather keep it in parity with production for now, but we may well come back to this in the future :)
